connect sys/&1@&2 as sysdba

set serveroutput on
exec dbms_output.put_line('#######create_user_agtf');


CREATE  TABLESPACE TB_AGTF
DATAFILE '&3/TB_AGTF01' SIZE 100M
AUTOEXTEND ON
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

-------TABLESPACE INDEX AGTF
--DROP TABLESPACE IDX_AGTF INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS; --(En COMMENTAIRE)
CREATE  TABLESPACE IDX_AGTF
DATAFILE '&3/IDX_AGTF01' SIZE 100M
AUTOEXTEND ON
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER "AGTF" PROFILE "DEFAULT" IDENTIFIED BY "&4" DEFAULT TABLESPACE "TB_AGTF" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "TB_AGTF" QUOTA UNLIMITED ON "IDX_AGTF" ACCOUNT UNLOCK;
GRANT CREATE ANY SYNONYM TO "AGTF";
GRANT CREATE VIEW TO "AGTF";
GRANT SELECT ANY TABLE TO "AGTF";
GRANT UNLIMITED TABLESPACE TO "AGTF";
GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "AGTF";
GRANT "CONNECT" TO "AGTF";
GRANT "RESOURCE" TO "AGTF";