connect sys/&1@&2 as sysdba

set serveroutput on
exec dbms_output.put_line('#######create tablespace srs_reloaded');


CREATE  TABLESPACE TB_SRS_RELOADED
DATAFILE '&3/TB_SRS_RELOADED01' SIZE 100M
AUTOEXTEND ON
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

CREATE  TABLESPACE IDX_SRS_RELOADED
DATAFILE '&3/IDX_SRS_RELOADED01' SIZE 100M
AUTOEXTEND ON
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;


exec dbms_output.put_line('#######create user ROOT-SRS');

CREATE USER "ROOT-SRS" PROFILE "DEFAULT" IDENTIFIED BY "&4" DEFAULT TABLESPACE "TB_SRS_RELOADED" TEMPORARY TABLESPACE "TEMP" QUOTA UNLIMITED ON "TB_SRS_RELOADED" QUOTA UNLIMITED ON "IDX_SRS_RELOADED" ACCOUNT UNLOCK;
GRANT CREATE ANY SYNONYM TO "ROOT-SRS";
GRANT CREATE VIEW TO "ROOT-SRS";
GRANT SELECT ANY TABLE TO "ROOT-SRS";
GRANT UNLIMITED TABLESPACE TO "ROOT-SRS";
GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "ROOT-SRS";
GRANT "CONNECT" TO "ROOT-SRS";
GRANT "RESOURCE" TO "ROOT-SRS";