-------SCRIPT NETTOYAGE 
DROP user ROOT-SRS cascade; 

DROP TABLESPACE TB_SRS_RELOADED INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_SRS_RELOADED INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

