-------SCRIPT NETTOYAGE 
DROP TABLESPACE IDX_NICOPE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE TB_WHOIS INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_WHOIS INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE TB_GERICO INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_GERICO INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE TB_BOA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_BOA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE TB_RALI INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_RALI INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE TB_AGTF INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_AGTF INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE TB_FICPOSTAUX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE IDX_FICPOSTAUX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP user NICOPE cascade; 
DROP user WHOIS cascade;
DROP user GERICO cascade;
DROP user BOA cascade;
DROP user RALI cascade;
DROP user AGTF cascade;
DROP user FICPOSTAUX cascade;

DROP TABLESPACE TB_NICOPE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

