/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package fr.afnic.commons.beans.mail.template;

/**
 * The EmailTemplateType Enumeration
 */
public enum EmailTemplateType {
    Gerico,
    GatewayIdentification,
    Boa,
    other;

}
