-- TRIGGER FOR SEQUENCE SEQ_ID_AUTHENTIFICATION FOR COLUMN ID_AUTHENTIFICATION IN TABLE AUTHENTIFICATION ---------

CREATE OR REPLACE TRIGGER "TS_AUTHENTIFICATION_SEQ_ID_A_5" BEFORE INSERT
ON "AUTHENTIFICATION" FOR EACH ROW
BEGIN
	:NEW."ID_AUTHENTIFICATION" := "SEQ_ID_AUTHENTIFICATION".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_AUTHENTIFICATION_SEQ_ID__5" AFTER UPDATE OF "ID_AUTHENTIFICATION"
ON "AUTHENTIFICATION" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_AUTHENTIFICATION" IN TABLE "AUTHENTIFICATION" AS IT USES SEQUENCE.');
END;
/
