-- TRIGGER FOR SEQUENCE SEQ_ID_CONTACT FOR COLUMN ID_CONTACT IN TABLE CONTACT ---------

CREATE OR REPLACE TRIGGER "TS_CONTACT_SEQ_ID_CONTACT" BEFORE INSERT
ON "CONTACT" FOR EACH ROW
BEGIN
	:NEW."ID_CONTACT" := "SEQ_ID_CONTACT".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_CONTACT_SEQ_ID_CONTACT" AFTER UPDATE OF "ID_CONTACT"
ON "CONTACT" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_CONTACT" IN TABLE "CONTACT" AS IT USES SEQUENCE.');
END;
/
