-- TRIGGER FOR SEQUENCE SEQ_ID_CONTRACTTYPE FOR COLUMN ID_CONTACTTYPE IN TABLE CONTACT_TYPE ---------

CREATE OR REPLACE TRIGGER "TS_CONTACT_TYPE_SEQ_ID_CONTR_0" BEFORE INSERT
ON "CONTACT_TYPE" FOR EACH ROW
BEGIN
	:NEW."ID_CONTACTTYPE" := "SEQ_ID_CONTRACTTYPE".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_CONTACT_TYPE_SEQ_ID_CONT_0" AFTER UPDATE OF "ID_CONTACTTYPE"
ON "CONTACT_TYPE" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_CONTACTTYPE" IN TABLE "CONTACT_TYPE" AS IT USES SEQUENCE.');
END;
/
