-- TRIGGER FOR SEQUENCE SEQ_ID_COUNTRY FOR COLUMN ID_COUNTRY IN TABLE COUNTRIES ---------

CREATE OR REPLACE TRIGGER "TS_COUNTRIES_SEQ_ID_COUNTRY" BEFORE INSERT
ON "COUNTRIES" FOR EACH ROW
BEGIN
	:NEW."ID_COUNTRY" := "SEQ_ID_COUNTRY".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_COUNTRIES_SEQ_ID_COUNTRY" AFTER UPDATE OF "ID_COUNTRY"
ON "COUNTRIES" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_COUNTRY" IN TABLE "COUNTRIES" AS IT USES SEQUENCE.');
END;
/
