-- TRIGGER FOR SEQUENCE SEQ_ID_NAMESERVER FOR COLUMN ID_NAMESERVER IN TABLE NAME_SERVERS ---------

CREATE OR REPLACE TRIGGER "TS_NAME_SERVERS_SEQ_ID_NAMES_5" BEFORE INSERT
ON "NAME_SERVERS" FOR EACH ROW
BEGIN
	:NEW."ID_NAMESERVER" := "SEQ_ID_NAMESERVER".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_NAME_SERVERS_SEQ_ID_NAME_5" AFTER UPDATE OF "ID_NAMESERVER"
ON "NAME_SERVERS" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_NAMESERVER" IN TABLE "NAME_SERVERS" AS IT USES SEQUENCE.');
END;
/
