-- TRIGGER FOR SEQUENCE SEQ_ID_POSTALADDRESS FOR COLUMN ID_POSTALADDRESS IN TABLE POSTAL_ADDRESSES ---------

CREATE OR REPLACE TRIGGER "TS_POSTAL_ADDRESSES_SEQ_ID_P_5" BEFORE INSERT
ON "POSTAL_ADDRESSES" FOR EACH ROW
BEGIN
	:NEW."ID_POSTALADDRESS" := "SEQ_ID_POSTALADDRESS".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_POSTAL_ADDRESSES_SEQ_ID__5" AFTER UPDATE OF "ID_POSTALADDRESS"
ON "POSTAL_ADDRESSES" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_POSTALADDRESS" IN TABLE "POSTAL_ADDRESSES" AS IT USES SEQUENCE.');
END;
/
