-- TRIGGER FOR SEQUENCE SEQ_ID_REGISTRAR_STATUS FOR COLUMN ID_STATUS IN TABLE REGISTRAR_STATUS ---------

CREATE OR REPLACE TRIGGER "TS_REGISTRAR_STATUS_SEQ_ID_R_0" BEFORE INSERT
ON "REGISTRAR_STATUS" FOR EACH ROW
BEGIN
	:NEW."ID_STATUS" := "SEQ_ID_REGISTRAR_STATUS".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_REGISTRAR_STATUS_SEQ_ID__0" AFTER UPDATE OF "ID_STATUS"
ON "REGISTRAR_STATUS" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_STATUS" IN TABLE "REGISTRAR_STATUS" AS IT USES SEQUENCE.');
END;
/
