-- TRIGGER FOR SEQUENCE SEQ_ID_REGISTRAR FOR COLUMN ID_REGISTRAR IN TABLE REGISTRARS ---------

CREATE OR REPLACE TRIGGER "TS_REGISTRARS_SEQ_ID_REGISTRAR" BEFORE INSERT
ON "REGISTRARS" FOR EACH ROW
BEGIN
	:NEW."ID_REGISTRAR" := "SEQ_ID_REGISTRAR".NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER "TSU_REGISTRARS_SEQ_ID_REGIST_5" AFTER UPDATE OF "ID_REGISTRAR"
ON "REGISTRARS" FOR EACH ROW
BEGIN
	RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN "ID_REGISTRAR" IN TABLE "REGISTRARS" AS IT USES SEQUENCE.');
END;
/
