CREATE OR REPLACE TRIGGER TRG_ZMVTINTERFACE_INSERT 
    BEFORE INSERT ON ZMVTINTERFACE 
    FOR EACH ROW 
BEGIN
    SELECT ZMVTINTERFACE_ZMI_ID_SEQ.nextval INTO :new.ZMI_ID FROM   DUAL;
	
	select sysdate into :new.ZMI_DTCREA from dual;
	select sysdate into :new.ZMI_DTMAJ from dual;
END; 
/
